### ISSUE TITLE
Running into error 503

### ISSUE THREAD

**Issue by felipellrocha** [eknowles/aws-cloudfront-preview-domains#1]
Hey,

Does this solution still work for you? I just tried following the tutorial, and am running into an error 503. Not sure what the issue is, honestly.

**Comment by korenyoni** [comment]
@felipellrocha it's not working for me either:

```bash
{
    "errorType": "TypeError",
    "errorMessage": "Cannot set property 'path' of undefined",
    "stack": [
        "TypeError: Cannot set property 'path' of undefined",
        "    at Runtime.exports.handler (/var/task/index.js:9:36)",
        "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
    ]
}
```

**Comment by korenyoni** [comment]
@felipellrocha 

It's fairly hard to debug because there are a lot of moving pieces. I ran into many 503's and here's a couple of tips:

* Are you using a custom origin with a S3 website domain or an S3 REST origin? I've only gotten these functions to work with the former.
* Do you have custom error responses? You will end up running into additional triggers of `origin-request` without the `x-forwarded-host` header.
* Is your CF distribution forwarding the `x-forwarded-host` to the origin? This is necessary.

Hope this helps.

**Comment by lcostea** [comment]
I also ran into HTTP 503 and the change I made to fix it was about reading the request object at the beginning of both scripts:
```
const request = event.Records[0].cf.request;
```
There are other changes on my setup, for example I am using a s3 origin (not a custom one) on the cloud front distribution, but I think the fix is reading the request accordingly to AWS examples - https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-examples.html
